export const initialFilters = {
  search: ['', false],
  generation: ['', false],
  egg_group: ['', false],
  types: [
    ['fire', false],
    ['water', false],
    ['grass', false],
    ['ghost', false],
    ['poison', false],
    ['psychic', false],
    ['fighting', false],
    ['flying', false],
    ['dark', false],
    ['steel', false],
    ['fairy', false],
    ['dragon', false],
    ['ice', false],
    ['rock', false],
    ['ground', false],
    ['normal', false],
    ['electric', false],
    ['bug', false],
    ['unknown', false],
    ['shadow', false],
  ],
  stats: [
    {
      name: 'hp',
      active: false,
      min: 0,
      max: 0,
    },
    {
      name: 'atk',
      active: false,
      min: 0,
      max: 0,
    },
    {
      name: 'def',
      active: false,
      min: 0,
      max: 0,
    },
    {
      name: 'spatk',
      active: false,
      min: 0,
      max: 0,
    },
    {
      name: 'spdef',
      active: false,
      min: 0,
      max: 0,
    },
    {
      name: 'speed',
      active: false,
      min: 0,
      max: 0,
    },
  ],
};
